### ISSUE TITLE
Local deployment TODO

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/rhub-server#4]
- [x] Make backend script work for Linux
- [x] Check with R package
- [x] Artifacts web server (with volume)
- [x] Deploy artifacts from Jenkins
- [x] Fix links in the e-mail message.
- [x] Fix web status  page when build has not started yet
- [x] Live log CSRF fix
- [x] Live log connection freeze fix
- [x] ~~Keepalive Jenkins job~~
- [x] cron job to clean up Jenkins
- [x] Docker volume for uploads
- [x] ~~External workers~~
- [x] Set PS4 in Jenkins
- [x] Ability to set CRAN mirror

The crossed ones are for later, in separate issues.
